name: Deploy To S3

on:
  push:
    branches:
      - "*" # Runs on push to any branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'ap-south-1'

      - name: Deploy to S3
        run: |
          # Path to the build output folder (adjust if needed)
          BUILD_DIR=build

          # Sync non-JS/CSS files first
          aws s3 sync $BUILD_DIR s3://html-basic-s3-aplication --delete \
            --exclude "*.js" --exclude "*.css" \
            --exclude ".git/*" --exclude ".github/*"

          # Sync JS files with correct content type
          find $BUILD_DIR -name "*.js" -exec \
            aws s3 cp {} s3://html-basic-s3-aplication/{} \
            --content-type "application/javascript" \;

          # Sync CSS files with correct content type
          find $BUILD_DIR -name "*.css" -exec \
            aws s3 cp {} s3://html-basic-s3-aplication/{} \
            --content-type "text/css" \;
